apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jambon.fullname" . }}
  labels:
    {{- include "jambon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jambon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jambon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "jambon.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jambon.fullname" . }}-config
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "jambon.fullname" . }}-secrets
                  key: DISCORD_TOKEN
                  optional: false
            - name: PROXMOX_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "jambon.fullname" . }}-secrets
                  key: PROXMOX_TOKEN_ID
                  optional: false
            - name: PROXMOX_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jambon.fullname" . }}-secrets
                  key: PROXMOX_TOKEN_SECRET
                  optional: false
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
