name: Bug report
description: Create a report to help us improve
labels: ["C-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run '...'
        2. See error
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Output of `cargo tree | grep jambon`
      render: text
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: OS, architecture, Rust version (`rustc --version`)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (with sensitive info redacted)
      render: text
